version: "3.8"

services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./static:/app/static
    environment:
      - FLASK_ENV=production